all: ex1 ex2 ex3

ex1: ex_02-01.c
	gcc ex_02-01.c -Wall -g -o ex_02-01
ex2: ex_02-02.c
	gcc ex_02-02.c -Wall -g -o ex_02-02
ex3: ex_02-03.c
	gcc ex_02-03.c -Wall -g -o ex_02-03
run:
	./ex_02-03
clean:
	rm ex_02-01 ex_02-02 ex_02-03
